
export const Paths = {
  Dashboard: "/dashboard",
  LogIn: "/",
  SignUp: "/sign-up",
  AboutUS: "/about-us",
  Cookies: "/cookies",
  ContactUS: '/contact-us',
  CommunityGuideLine: "/community-guidelines",
  PrivatePolicy: '/policy',
  Help: '/help',
  ForgotPassword: "/forgot-password",
  InviteFriend: "/invite-friend",
  PrivacySetting: "/privacy-setting",
  ResetPassword: "/reset-password",
  BlockedUser: "/block-userlist",
  ProfileSetUp: "/profile",
  Home: "/user-profile",
  UserProfileDetail: "/user-profile/:id",
  Favourite: "/favourite",
  ProfileSetting: '/profile-setting',
  Following: '/following',
  Follower: '/followers',
  FollowingOtherUserDetail: '/following/:id',
  FollowerOtherUserDetail: '/followers/:id',
  CreatePost: "/create-post",
  Notifications: '/notifications',
  PublicReactions: '/public-reactions',
  UpdatePost: "/create-post/:id",
  UserChat: '/chat'
};
